openapi: 3.0.0
info:
  title: Client Consent
  version: 1.0.1
  contact:
    name: API Source
    email: support@hslynk.com
    url: https://github.com/hmis-api/client-consent-api
  # Name of the license and a URL to the license description.
  license:
    name: Open Source License
    url: https://github.com/hmis-api/client-consent-api/blob/master/LICENSE
  description: |
       **Note :**
              Please note that the partial updates are supported via PUT APIs. However, Note that If "null" value is passed for any element, in the PUT request body, it will be ignored. An empty string value should be sent (instead of "null" value) for the elements that need to be updated with NULL values.
servers:
  - url: 'https://api.hmislynk.com/global-api/'
paths:
  '/clients/{clientid}/consents':
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                consent:
                  consentId: 2a484199-e2cb-4044-bee9-f0bbcea7eff3
              schema:
                {
                  "type": "object",
                  "required": [
                    "consent"
                  ],
                  "properties": {
                    "consent": {
                      "type": "object",
                      "required": [
                        "consentId"
                      ],
                      "properties": {
                        "consentId": {
                          "type": "string",
                          "format": "uuid",
                        }
                      }
                    }
                  }
                }
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_NOT_FOUND
                    message: 'Client not found : e9a4a447-833f-4c29-a3b6-f966a0a753aa'
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: >-
        Create client consent. NOTE- A client consent will also be created when
        a consent request is approved.
      operationId: POST_clients-clientid-consents
      requestBody:
        content:
          application/json:
            example:
              consent:
                clientId: 4cfe2ac2-43af-4d6d-9ee8-0e8fac5e3dc8
                startTime: '01-16-2017 14:37:20.351'
                endTime: '02-16-2017 14:37:20.351'
                consentEntities:
                  consentEntities:
                    - consentTypeId: bd4f1ad9-5e6e-495d-9d49-b8fdcff38bd9
                      consentEntityId: 0d61a895-197a-4e4c-8626-a8b78d9e18f1
                    - consentTypeId: 13954e42-e873-11e6-bf01-fe55135034f3
                      consentEntityId: 139554c8-e873-11e6-bf01-fe55135034f3
            schema:
              {
                "type": "object",
                "required": [
                  "consent"
                ],
                "properties": {
                  "consent": {
                    "type": "object",
                    "required": [
                      "clientId",
                      "startTime",
                      "endTime",
                      "consentEntities"
                    ],
                    "properties": {
                      "clientId": {
                        "type": "string",
                        "format": "uuid",
                      },
                      "startTime": {
                        "type": "string",
                        "format": "MM-dd-YYYY HH:mm:ss.SSS"
                      },
                      "endTime": {
                        "type": "string",
                        "format": "MM-dd-YYYY HH:mm:ss.SSS"
                      },
                      "consentEntities": {
                        "type": "object",
                        "required": [
                          "consentEntities"
                        ],
                        "properties": {
                          "consentEntities": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "required": [
                                "consentTypeId",
                                "consentEntityId"
                              ],
                              "properties": {
                                "consentTypeId": {
                                  "type": "string",
                                  "format": "uuid",
                                },
                                "consentEntityId": {
                                  "type": "string",
                                  "format": "uuid",
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
        required: true
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                consents:
                  pagination:
                    from: 0
                    returned: 1
                    total: 1
                    maximum: 30
                    sort: {}
                  consents:
                    - consent:
                        consentId: 2a484199-e2cb-4044-bee9-f0bbcea7eff3
                        clientId: 4cfe2ac2-43af-4d6d-9ee8-0e8fac5e3dc8
                        startTime: '01-16-2017 14:37:20.351'
                        status: APPROVED
                        endTime: '01-16-2017 14:37:20.351'
                        consentEntities:
                          consentEntities:
                            - consentTypeId: bd4f1ad9-5e6e-495d-9d49-b8fdcff38bd9
                              consentEntityId: 0d61a895-197a-4e4c-8626-a8b78d9e18f1
              schema:
                {
                  "type": "object",
                  "required": [
                    "consents"
                  ],
                  "properties": {
                    "consents": {
                      "type": "object",
                      "required": [
                        "pagination",
                        "consents"
                      ],
                      "properties": {
                        "pagination": {
                          "type": "object",
                          "required": [
                            "from",
                            "returned",
                            "total",
                            "maximum",
                            "sort"
                          ],
                          "properties": {
                            "from": {
                              "type": "integer"
                            },
                            "returned": {
                              "type": "integer"
                            },
                            "total": {
                              "type": "integer"
                            },
                            "maximum": {
                              "type": "integer"
                            },
                            "sort": {
                              "type": "object"
                            }
                          }
                        },
                        "consents": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "required": [
                              "consent"
                            ],
                            "properties": {
                              "consent": {
                                "type": "object",
                                "required": [
                                  "consentId",
                                  "clientId",
                                  "startTime",
                                  "status",
                                  "endTime",
                                  "consentEntities"
                                ],
                                "properties": {
                                  "consentId": {
                                    "type": "string",
                                    "format": "uuid",
                                  },
                                  "clientId": {
                                    "type": "string",
                                    "format": "uuid",
                                  },
                                  "startTime": {
                                    "type": "string",
                                    "format": "MM-dd-YYYY HH:mm:ss.SSS"
                                  },
                                  "status": {
                                    "type": "string",
                                  },
                                  "endTime": {
                                    "type": "string",
                                    "format": "MM-dd-YYYY HH:mm:ss.SSS"
                                  },
                                  "consentEntities": {
                                    "type": "object",
                                    "required": [
                                      "consentEntities"
                                    ],
                                    "properties": {
                                      "consentEntities": {
                                        "type": "array",
                                        "items": {
                                          "type": "object",
                                          "required": [
                                            "consentTypeId",
                                            "consentEntityId"
                                          ],
                                          "properties": {
                                            "consentTypeId": {
                                              "type": "string",
                                              "format": "uuid",
                                            },
                                            "consentEntityId": {
                                              "type": "string",
                                              "format": "uuid",
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
      description: Get consents of a client
      operationId: GET_clients-clientid-consents
    parameters:
      - name: clientid
        in: path
        required: true
        schema:
          type: string
  '/clients/{clientid}/consents/{consentid}':
    put:
      responses:
        '201':
          description: ''
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_CONSENT_NOT_FOUND
                    message: >-
                      Client consent not found :
                      e9a4a447-833f-4c29-a3b6-f966a0a753aa
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: >-
        Update a client consent. The purpose of the API is to 1. Update the
        status of a consent (Allowed values APPROVED / REJECTED) 2. Update the
        status effective dates. 3. Update the consent entity types.
      operationId: PUT_clients-clientid-consents-consentid
      requestBody:
        content:
          application/json:
            example:
              consent:
                clientId: 4cfe2ac2-43af-4d6d-9ee8-0e8fac5e3dc8
                startTime: '01-16-2017 14:37:20.351'
                endTime: '02-16-2017 14:37:20.351'
                consentEntities:
                  consentEntities:
                    - consentTypeId: bd4f1ad9-5e6e-495d-9d49-b8fdcff38bd9
                      consentEntityId: 0d61a895-197a-4e4c-8626-a8b78d9e18f1
                    - consentTypeId: 13954e42-e873-11e6-bf01-fe55135034f3
                      consentEntityId: 139554c8-e873-11e6-bf01-fe55135034f3
            schema:
              {
                "type": "object",
                "required": [
                  "consent"
                ],
                "properties": {
                  "consent": {
                    "type": "object",
                    "required": [
                      "clientId",
                      "startTime",
                      "endTime",
                      "consentEntities"
                    ],
                    "properties": {
                      "clientId": {
                        "type": "string",
                        "format": "uuid",
                      },
                      "startTime": {
                        "type": "string",
                        "format": "MM-dd-YYYY HH:mm:ss.SSS"
                      },
                      "endTime": {
                        "type": "string",
                        "format": "MM-dd-YYYY HH:mm:ss.SSS"
                      },
                      "consentEntities": {
                        "type": "object",
                        "required": [
                          "consentEntities"
                        ],
                        "properties": {
                          "consentEntities": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "required": [
                                "consentTypeId",
                                "consentEntityId"
                              ],
                              "properties": {
                                "consentTypeId": {
                                  "type": "string",
                                  "format": "uuid",
                                },
                                "consentEntityId": {
                                  "type": "string",
                                  "format": "uuid",
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
        required: true
    delete:
      responses:
        '201':
          description: ''
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_CONSENT_NOT_FOUND
                    message: >-
                      Client consent not found :
                      e9a4a447-833f-4c29-a3b6-f966a0a753aa
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: Delete a client consent
      operationId: DELETE_clients-clientid-consents-consentid
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                consent:
                  consentId: 2a484199-e2cb-4044-bee9-f0bbcea7eff3
                  clientId: 4cfe2ac2-43af-4d6d-9ee8-0e8fac5e3dc8
                  startTime: '01-16-2017 14:37:20.351'
                  status: APPROVED
                  endTime: '01-16-2017 14:37:20.351'
                  consentEntities:
                    consentEntities:
                      - consentTypeId: bd4f1ad9-5e6e-495d-9d49-b8fdcff38bd9
                        consentEntityId: 0d61a895-197a-4e4c-8626-a8b78d9e18f1
              schema:
                {
                  "type": "object",
                  "required": [
                    "consent"
                  ],
                  "properties": {
                    "consent": {
                      "type": "object",
                      "required": [
                        "consentId",
                        "clientId",
                        "startTime",
                        "status",
                        "endTime",
                        "consentEntities"
                      ],
                      "properties": {
                        "consentId": {
                          "type": "string",
                          "format": "uuid",
                        },
                        "clientId": {
                          "type": "string",
                          "format": "uuid",
                        },
                        "startTime": {
                          "type": "string",
                          "format": "MM-dd-YYYY HH:mm:ss.SSS"
                        },
                        "status": {
                          "type": "string",
                        },
                        "endTime": {
                          "type": "string",
                          "format": "MM-dd-YYYY HH:mm:ss.SSS"
                        },
                        "consentEntities": {
                          "type": "object",
                          "required": [
                            "consentEntities"
                          ],
                          "properties": {
                            "consentEntities": {
                              "type": "array",
                              "items": {
                                "type": "object",
                                "required": [
                                  "consentTypeId",
                                  "consentEntityId"
                                ],
                                "properties": {
                                  "consentTypeId": {
                                    "type": "string",
                                    "format": "uuid",
                                  },
                                  "consentEntityId": {
                                    "type": "string",
                                    "format": "uuid",
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_CONSENT_NOT_FOUND
                    message: >-
                      Client consent not found :
                      e9a4a447-833f-4c29-a3b6-f966a0a753aa
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: Get a client consent details
      operationId: GET_clients-clientid-consents-consentid
    parameters:
      - name: consentid
        in: path
        required: true
        schema:
          type: string
      - name: clientid
        in: path
        required: true
        schema:
          type: string
  '/clients/{clientid}/consents/{consentid}/documents':
    post:
      responses:
        '201':
          description: ''
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_CONSENT_NOT_FOUND
                    message: >-
                      Client consent not found :
                      e9a4a447-833f-4c29-a3b6-f966a0a753aa
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: >
        Uploads the consent document (Verbal / signed document) for the client
        for a specific consent.  The content type should be multipart/form-data
        ( Content-Type: multipart/form-data).
      operationId: POST_clients-clientid-consents-consentid-documents
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                formData:
                  example: >
                    Content-Type: multipart/form-data;
                    boundary=WebKitFormBoundarytujNY4RwDez6d3Hk


                    --WebKitFormBoundarytujNY4RwDez6d3Hk

                    Content-Disposition: form-data; name="json"

                    Content-Type: application/json


                    { "type": "documents","remarks":"Project 1 consent document"
                    }


                    --WebKitFormBoundarytujNY4RwDez6d3Hk--

                    Content-Disposition: form-data; name="image";
                    filename="image.jpg"

                    Content-Type: application/octet-stream


                    ... content of image.jpg ...


                    --WebKitFormBoundarytujNY4RwDez6d3Hk--
                  type: string
              type: object
        required: true
    get:
      responses:
        '200':
          description: ''
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_CONSENT_NOT_FOUND
                    message: >-
                      Client consent not found :
                      e9a4a447-833f-4c29-a3b6-f966a0a753aa
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: |
        Downloads all the consent documents associated with a specific consent.
      operationId: GET_clients-clientid-consents-consentid-documents
    parameters:
      - name: consentid
        in: path
        required: true
        schema:
          type: string
      - name: clientid
        in: path
        required: true
        schema:
          type: string
  '/clients/{clientid}/consentrequests':
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                consentRequest:
                  consentRequestId: 2a484199-e2cb-4044-bee9-f0bbcea7eff3
              schema:
                {
                  "type": "object",
                  "required": [
                    "consentRequest"
                  ],
                  "properties": {
                    "consentRequest": {
                      "type": "object",
                      "required": [
                        "consentRequestId"
                      ],
                      "properties": {
                        "consentRequestId": {
                          "type": "string",
                          "format": "uuid",
                        }
                      }
                    }
                  }
                }
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_NOT_FOUND
                    message: 'Client not found : e9a4a447-833f-4c29-a3b6-f966a0a753aa'
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: >-
        Create client consent request. A consent request can be made for a
        specific (or multiple) consent entity types and for a specific duration.
        Initially the status of the consent request will be set to "REQUESTED".
      operationId: POST_clients-clientid-consentrequests
      requestBody:
        content:
          application/json:
            example:
              consentRequest:
                clientId: 4cfe2ac2-43af-4d6d-9ee8-0e8fac5e3dc8
                consentRequestedFrom: '01-16-2017 14:37:20.351'
                consentRequestedTo: '02-16-2017 14:37:20.351'
                consentEntities:
                  consentEntities:
                    - consentTypeId: bd4f1ad9-5e6e-495d-9d49-b8fdcff38bd9
                      consentEntityId: 0d61a895-197a-4e4c-8626-a8b78d9e18f1
            schema:
              {
                "type": "object",
                "required": [
                  "consentRequest"
                ],
                "properties": {
                  "consentRequest": {
                    "type": "object",
                    "required": [
                      "clientId",
                      "consentRequestedFrom",
                      "consentRequestedTo",
                      "consentEntities"
                    ],
                    "properties": {
                      "clientId": {
                        "type": "string",
                        "format": "uuid",
                      },
                      "consentRequestedFrom": {
                        "type": "string",
                        "format": "MM-dd-YYYY HH:mm:ss.SSS"

                      },
                      "consentRequestedTo": {
                        "type": "string",
                        "format": "MM-dd-YYYY HH:mm:ss.SSS"
                      },
                      "consentEntities": {
                        "type": "object",
                        "required": [
                          "consentEntities"
                        ],
                        "properties": {
                          "consentEntities": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "required": [
                                "consentTypeId",
                                "consentEntityId"
                              ],
                              "properties": {
                                "consentTypeId": {
                                  "type": "string",
                                  "format": "uuid",
                                },
                                "consentEntityId": {
                                  "type": "string",
                                  "format": "uuid",
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
        required: true
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                consentRequests:
                  pagination:
                    from: 0
                    returned: 1
                    total: 1
                    maximum: 30
                    sort: {}
                  consentRequests:
                    - consentRequest:
                        consentRequestId: 2a484199-e2cb-4044-bee9-f0bbcea7eff3
                        clientId: 4cfe2ac2-43af-4d6d-9ee8-0e8fac5e3dc8
                        consentRequestedFrom: '01-16-2017 14:37:20.351'
                        status: APPROVED
                        consentEntities:
                          consentEntities:
                            - consentTypeId: bd4f1ad9-5e6e-495d-9d49-b8fdcff38bd9
                              consentEntityId: 0d61a895-197a-4e4c-8626-a8b78d9e18f1
              schema:
                {
                  "type": "object",
                  "required": [
                    "consentRequests"
                  ],
                  "properties": {
                    "consentRequests": {
                      "type": "object",
                      "required": [
                        "pagination",
                        "consentRequests"
                      ],
                      "properties": {
                        "pagination": {
                          "type": "object",
                          "required": [
                            "from",
                            "returned",
                            "total",
                            "maximum",
                            "sort"
                          ],
                          "properties": {
                            "from": {
                              "type": "integer"
                            },
                            "returned": {
                              "type": "integer"
                            },
                            "total": {
                              "type": "integer"
                            },
                            "maximum": {
                              "type": "integer"
                            },
                            "sort": {
                              "type": "object"
                            }
                          }
                        },
                        "consentRequests": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "required": [
                              "consentRequest"
                            ],
                            "properties": {
                              "consentRequest": {
                                "type": "object",
                                "required": [
                                  "consentRequestId",
                                  "clientId",
                                  "consentRequestedFrom",
                                  "status",
                                  "consentEntities"
                                ],
                                "properties": {
                                  "consentRequestId": {
                                    "type": "string",
                                    "format": "uuid",
                                  },
                                  "clientId": {
                                    "type": "string",
                                    "format": "uuid",
                                  },
                                  "consentRequestedFrom": {
                                    "type": "string",
                                    "format": "MM-dd-YYYY HH:mm:ss.SSS"
                                  },
                                  "status": {
                                    "type": "string",
                                  },
                                  "consentEntities": {
                                    "type": "object",
                                    "required": [
                                      "consentEntities"
                                    ],
                                    "properties": {
                                      "consentEntities": {
                                        "type": "array",
                                        "items": {
                                          "type": "object",
                                          "required": [
                                            "consentTypeId",
                                            "consentEntityId"
                                          ],
                                          "properties": {
                                            "consentTypeId": {
                                              "type": "string",
                                              "format": "uuid",
                                            },
                                            "consentEntityId": {
                                              "type": "string",
                                              "format": "uuid",
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
      description: Get consent requests of a client
      operationId: GET_clients-clientid-consentrequests
    parameters:
      - name: clientid
        in: path
        required: true
        schema:
          type: string
  '/clients/{clientid}/consentrequests/{consentrequestid}':
    put:
      responses:
        '201':
          description: ''
        '403':
          description: ''
          content:
            application/json:
                schema:
                  {
                    "type": "object",
                    "required": [
                      "errors"
                    ],
                    "properties": {
                      "errors": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "required": [
                            "code",
                            "message"
                          ],
                          "properties": {
                            "code": {
                              "type": "string",
                            },
                            "message": {
                              "type": "string",
                            }
                          }
                        }
                      }
                    }
                  }
                example:
                  errors:
                    - code: CANNOT_UPDATE_CONSENT_REQUEST
                      message: consent request already approved / rejected.
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_CONSENT_REQUEST_NOT_FOUND
                    message: >-
                      Client consent request not found :
                      e9a4a447-833f-4c29-a3b6-f966a0a753aa
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: >-
        Update a client consent request. Consent request can be updated only
        when the status is still in "REQUESTED" state.
      operationId: PUT_clients-clientid-consentrequests-consentrequestid
      requestBody:
        content:
          application/json:
            example:
              consentRequest:
                clientId: 4cfe2ac2-43af-4d6d-9ee8-0e8fac5e3dc8
                consentRequestedFrom: '01-16-2017 14:37:20.351'
                consentRequestedTo: '02-16-2017 14:37:20.351'
                consentEntities:
                  consentEntities:
                    - consentTypeId: bd4f1ad9-5e6e-495d-9d49-b8fdcff38bd9
                      consentEntityId: 0d61a895-197a-4e4c-8626-a8b78d9e18f1
            schema:
              {
                "type": "object",
                "required": [
                  "consentRequest"
                ],
                "properties": {
                  "consentRequest": {
                    "type": "object",
                    "required": [
                      "clientId",
                      "consentRequestedFrom",
                      "consentRequestedTo",
                      "consentEntities"
                    ],
                    "properties": {
                      "clientId": {
                        "type": "string",
                        "format": "uuid",
                      },
                      "consentRequestedFrom": {
                        "type": "string",
                        "format": "MM-dd-YYYY HH:mm:ss.SSS"
                      },
                      "consentRequestedTo": {
                        "type": "string",
                        "format": "MM-dd-YYYY HH:mm:ss.SSS"
                      },
                      "consentEntities": {
                        "type": "object",
                        "required": [
                          "consentEntities"
                        ],
                        "properties": {
                          "consentEntities": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "required": [
                                "consentTypeId",
                                "consentEntityId"
                              ],
                              "properties": {
                                "consentTypeId": {
                                  "type": "string",
                                  "format": "uuid",
                                },
                                "consentEntityId": {
                                  "type": "string",
                                  "format": "uuid",
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
        required: true
    delete:
      responses:
        '201':
          description: ''
        '403':
          description: ''
          content:
            application/json:
                schema:
                  {
                    "type": "object",
                    "required": [
                      "errors"
                    ],
                    "properties": {
                      "errors": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "required": [
                            "code",
                            "message"
                          ],
                          "properties": {
                            "code": {
                              "type": "string",
                            },
                            "message": {
                              "type": "string",
                            }
                          }
                        }
                      }
                    }
                  }
                example:
                  errors:
                    - code: CANNOT_DELETE_CONSENT_REQUEST
                      message: consent request already approved / rejected.
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_CONSENT_REQUEST_NOT_FOUND
                    message: >-
                      Client consent request not found :
                      e9a4a447-833f-4c29-a3b6-f966a0a753aa
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: >-
        Delete a client consent request. Consent request can be deleted only
        when the status is still in "REQUESTED" state.
      operationId: DELETE_clients-clientid-consentrequests-consentrequestid
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                consentRequest:
                  consentRequestId: 2a484199-e2cb-4044-bee9-f0bbcea7eff3
                  clientId: 4cfe2ac2-43af-4d6d-9ee8-0e8fac5e3dc8
                  status: REQUESTED
                  consentRequestedFrom: '01-16-2017 14:37:20.351'
                  consentRequestedTo: '02-16-2017 14:37:20.351'
                  consentEntities:
                    consentEntities:
                      - consentTypeId: bd4f1ad9-5e6e-495d-9d49-b8fdcff38bd9
                        consentEntityId: 0d61a895-197a-4e4c-8626-a8b78d9e18f1
              schema:
                {
                  "type": "object",
                  "required": [
                    "consentRequest"
                  ],
                  "properties": {
                    "consentRequest": {
                      "type": "object",
                      "required": [
                        "consentRequestId",
                        "clientId",
                        "status",
                        "consentRequestedFrom",
                        "consentRequestedTo",
                        "consentEntities"
                      ],
                      "properties": {
                        "consentRequestId": {
                          "type": "string",
                          "format": "uuid",
                        },
                        "clientId": {
                          "type": "string",
                          "format": "uuid",
                        },
                        "status": {
                          "type": "string",
                        },
                        "consentRequestedFrom": {
                          "type": "string",
                          "format": "MM-dd-YYYY HH:mm:ss.SSS"
                        },
                        "consentRequestedTo": {
                          "type": "string",
                          "format": "MM-dd-YYYY HH:mm:ss.SSS"
                        },
                        "consentEntities": {
                          "type": "object",
                          "required": [
                            "consentEntities"
                          ],
                          "properties": {
                            "consentEntities": {
                              "type": "array",
                              "items": {
                                "type": "object",
                                "required": [
                                  "consentTypeId",
                                  "consentEntityId"
                                ],
                                "properties": {
                                  "consentTypeId": {
                                    "type": "string",
                                    "format": "uuid",
                                  },
                                  "consentEntityId": {
                                    "type": "string",
                                    "format": "uuid",
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_CONSENT_REQUEST_NOT_FOUND
                    message: >-
                      Client consent request not found :
                      e9a4a447-833f-4c29-a3b6-f966a0a753aa
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: Get details for a specific client consent request.
      operationId: GET_clients-clientid-consentrequests-consentrequestid
    parameters:
      - name: consentrequestid
        in: path
        required: true
        schema:
          type: string
      - name: clientid
        in: path
        required: true
        schema:
          type: string
  '/clients/{clientid}/consentrequests/{consentrequestid}/statuses':
    put:
      responses:
        '404':
          description: ''
          content:
            application/json:
              example:
                errors:
                  - code: CLIENT_CONSENT_NOT_FOUND
                    message: >-
                      Client consent not found :
                      e9a4a447-833f-4c29-a3b6-f966a0a753aa
              schema:
                {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "code",
                          "message"
                        ],
                        "properties": {
                          "code": {
                            "type": "string",
                          },
                          "message": {
                            "type": "string",
                          }
                        }
                      }
                    }
                  }
                }
      description: >-
        Approve or Reject client consent request. Once consent request is
        approved a new consent will be created for the requester project group
        and for the consent entity. The consent request, cannot be modified any
        further as it is already approved. Any changes to the duration of the
        consent etc. can be done on the consent directly. Allowed values for the
        consent request status are APPROVED / REJECTED.
      operationId: PUT_clients-clientid-consentrequests-consentrequestid-statuses
      requestBody:
        content:
          application/json:
            example:
              - consentRequestStatus:
                  approvalStatus: APPROVED
                  approvalStatusEffectiveFromDate: '01-16-2017 14:37:20.351'
                  approvalStatusEffectiveToDate: '01-24-2017 14:37:20.351'
                  remarks: ' Approved'
              - consentRequestStatus:
                  approvalStatus: REJECTED
                  approvalStatusEffectiveFromDate: '01-16-2017 14:37:20.351'
                  approvalStatusEffectiveToDate: '01-24-2017 14:37:20.351'
                  remarks: ' Client did not honor the request'
            schema:
              {
                "type": "array",
                "items": {
                  "type": "object",
                  "required": [
                    "consentRequestStatus"
                  ],
                  "properties": {
                    "consentRequestStatus": {
                      "type": "object",
                      "required": [
                        "approvalStatus",
                        "approvalStatusEffectiveFromDate",
                        "approvalStatusEffectiveToDate",
                        "remarks"
                      ],
                      "properties": {
                        "approvalStatus": {
                          "type": "string",
                        },
                        "approvalStatusEffectiveFromDate": {
                          "type": "string",
                          "format": "MM-dd-YYYY HH:mm:ss.SSS"
                        },
                        "approvalStatusEffectiveToDate": {
                          "type": "string",
                          "format": "MM-dd-YYYY HH:mm:ss.SSS"
                        },
                        "remarks": {
                          "type": "string",
                        }
                      }
                    }
                  }
                }
              }
        required: true
    parameters:
      - name: consentrequestid
        in: path
        required: true
        schema:
          type: string
      - name: clientid
        in: path
        required: true
        schema:
          type: string
  /consententitytypes:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
                schema:
                  {
                    "type": "object",
                    "required": [
                      "consententitytypes"
                    ],
                    "properties": {
                      "consententitytypes": {
                        "type": "object",
                        "required": [
                          "pagination",
                          "consententitytypes"
                        ],
                        "properties": {
                          "pagination": {
                            "type": "object",
                            "required": [
                              "from",
                              "returned",
                              "total",
                              "maximum",
                              "sort"
                            ],
                            "properties": {
                              "from": {
                                "type": "integer"
                              },
                              "returned": {
                                "type": "integer"
                              },
                              "total": {
                                "type": "integer"
                              },
                              "maximum": {
                                "type": "integer"
                              },
                              "sort": {
                                "type": "object"
                              }
                            }
                          },
                          "consententitytypes": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "required": [
                                "consententitytype"
                              ],
                              "properties": {
                                "consententitytype": {
                                  "type": "object",
                                  "required": [
                                    "entityTypeId",
                                    "entityType"
                                  ],
                                  "properties": {
                                    "entityTypeId": {
                                      "type": "string",
                                      "format": "uuid",
                                    },
                                    "entityType": {
                                      "type": "string",
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                example:
                  consententitytypes:
                    pagination:
                      from: 0
                      returned: 2
                      total: 30
                      maximum: 30
                      sort: {}
                    consententitytypes:
                      - consententitytype:
                          entityTypeId: 2a484199-e2cb-4044-bee9-f0bbcea7eff3
                          entityType: Project
                      - consententitytype:
                          entityTypeId: 2a484200-e2cb-4044-bee9-f0bbcea7eff3
                          entityType: coc
      description: Get consent entity types.
      operationId: GET_consententitytypes
components:

  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    oauth_2_0:
      description: |
        The HMIS API supports OAuth 2.0 for authenticating all API requests.
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://hmislynk.com/hmis-authorization-service/rest/token'
          scopes:
            user: ''
            administrator: ''
  links: {}
  callbacks: {}
